apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dagster-webserver
  namespace: dagster
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dagster.localtest.me
      secretName: dagster-tls
  rules:
    - host: dagster.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dagster-dagster-webserver
                port:
                  number: 80
