dagsterWebserver:
  service:
    type: ClusterIP
  workspace:
    enabled: true
    servers:
      - host: "dagster-user-deployments-k8s-example-user-code-1"
        port: 3030
        name: "user-code-example"

postgresql:
  enabled: true
  auth:
    username: dagster
    password: dagster
    database: dagster
  primary:
    persistence:
      enabled: false
